package io.heapy.kwasm.bindgen.ksp

internal class BindingSourceRenderer(
    private val target: BindingTarget = BindingTarget.PORTABLE,
) {
    fun render(boundary: BoundaryModel): String = buildString {
        appendLine("// Generated by kwasm bindgen. Do not edit.")
        appendLine("@file:OptIn(io.heapy.kwasm.ExperimentalKwasmApi::class)")
        appendLine("@file:Suppress(\"RedundantVisibilityModifier\")")
        appendLine()
        if (boundary.packageName.isNotEmpty()) {
            appendLine("package ${boundary.packageName}")
            appendLine()
        }
        renderDescriptor(boundary)
        appendLine()
        renderClient(boundary, ClientKind.HOST)
        appendLine()
        renderHostImports(boundary)
        appendLine()
        renderClient(boundary, ClientKind.GUEST)
        appendLine()
        renderGuestExports(boundary)
    }

    private fun StringBuilder.renderDescriptor(boundary: BoundaryModel) {
        appendLine("public object ${identifier(boundary.generatedBaseName)} {")
        appendLine(
            "    public val descriptor: $API.WasmBoundaryDescriptor = " +
                "$API.WasmBoundaryDescriptor(",
        )
        appendLine("        kotlinType = ${stringLiteral(boundary.qualifiedName)},")
        appendLine("        wireName = ${stringLiteral(boundary.wireName)},")
        appendLine("        abiVersion = $API.WasmAbiCodec.VERSION,")
        if (boundary.functions.isEmpty()) {
            appendLine("        functions = emptyList(),")
        } else {
            appendLine("        functions = listOf(")
            boundary.functions.forEach { function ->
                appendLine("            $API.WasmFunctionDescriptor(")
                appendLine("                kotlinName = ${stringLiteral(function.kotlinName)},")
                appendLine("                wireName = ${stringLiteral(function.wireName)},")
                if (function.parameters.isEmpty()) {
                    appendLine("                parameters = emptyList(),")
                } else {
                    appendLine("                parameters = listOf(")
                    function.parameters.forEach { parameter ->
                        appendLine(
                            "                    $API.WasmParameterDescriptor(" +
                                "name = ${stringLiteral(parameter.name)}, " +
                                "type = $API.WasmAbiType.${parameter.type.abiEnumName}),",
                        )
                    }
                    appendLine("                ),")
                }
                appendLine(
                    "                returnType = " +
                        "$API.WasmAbiType.${function.returnType.abiEnumName},",
                )
                appendLine("                isSuspend = ${function.isSuspend},")
                appendLine("            ),")
            }
            appendLine("        ),")
        }
        appendLine("    )")
        appendLine("}")
    }

    private fun StringBuilder.renderClient(
        boundary: BoundaryModel,
        kind: ClientKind,
    ) {
        val suffix = if (kind == ClientKind.HOST) "HostClient" else "GuestClient"
        val invokerType =
            if (kind == ClientKind.HOST) "$API.WasmHostInvoker" else "$API.WasmGuestInvoker"
        val defaultInvoker =
            if (kind == ClientKind.GUEST && target == BindingTarget.WASM) {
                " = io.heapy.kwasm.bindgen.generated.KwasmWasmGuestInvoker"
            } else {
                ""
            }
        appendLine(
            "public class ${identifier(boundary.interfaceName + suffix)}(",
        )
        appendLine("    private val invoker: $invokerType$defaultInvoker,")
        appendLine(") : ${identifier(boundary.interfaceName)} {")
        boundary.functions.forEach { function ->
            renderClientFunction(boundary, function, kind)
        }
        appendLine("}")
    }

    private fun StringBuilder.renderClientFunction(
        boundary: BoundaryModel,
        function: FunctionModel,
        kind: ClientKind,
    ) {
        val suspendPrefix = if (function.isSuspend) "suspend " else ""
        val parameters = function.parameters.joinToString(", ") {
            "${identifier(it.name)}: ${it.type.kotlinSource}"
        }
        appendLine(
            "    override ${suspendPrefix}fun ${identifier(function.kotlinName)}" +
                "($parameters): ${function.returnType.kotlinSource} {",
        )
        val resultName = uniqueIdentifier("_kwasmResult", function.parameters.map { it.name })
        val valuesName = uniqueIdentifier("_kwasmValues", function.parameters.map { it.name })
        val invocationName =
            if (kind == ClientKind.HOST && function.isSuspend) "invokeSuspend" else "invoke"
        appendLine(
            "        val $resultName = this.invoker.$invocationName(" +
                "${stringLiteral(boundary.wireName)}, " +
                "${stringLiteral(function.wireName)}, " +
                encodeParameters(function.parameters) +
                ")",
        )
        renderDecodeReturn(
            returnType = function.returnType,
            encodedResultName = resultName,
            decodedValuesName = valuesName,
            indent = "        ",
        )
        appendLine("    }")
    }

    private fun StringBuilder.renderHostImports(boundary: BoundaryModel) {
        appendLine("public class ${identifier(boundary.interfaceName + "HostImports")}(")
        appendLine("    private val implementation: ${identifier(boundary.interfaceName)},")
        appendLine(") {")
        if (boundary.functions.isEmpty()) {
            appendLine("    public fun bindings(): kotlin.collections.List<$API.WasmImportBinding> =")
            appendLine("        emptyList()")
        } else {
            appendLine("    public fun bindings(): kotlin.collections.List<$API.WasmImportBinding> =")
            appendLine("        listOf(")
            boundary.functions.forEach { function ->
                appendLine("            $API.WasmImportBinding(")
                appendLine("                boundary = ${stringLiteral(boundary.wireName)},")
                appendLine("                function = ${stringLiteral(function.wireName)},")
                appendLine("                isSuspend = ${function.isSuspend},")
                appendLine("            ) { _kwasmPayload ->")
                renderDispatchBody(
                    function = function,
                    payloadName = "_kwasmPayload",
                    indent = "                ",
                    explicitReturn = false,
                )
                appendLine("            },")
            }
            appendLine("        )")
        }
        appendLine("}")
    }

    private fun StringBuilder.renderGuestExports(boundary: BoundaryModel) {
        appendLine("public class ${identifier(boundary.interfaceName + "GuestExports")}(")
        appendLine("    private val implementation: ${identifier(boundary.interfaceName)},")
        appendLine(") {")
        if (boundary.functions.isEmpty()) {
            appendLine("    public fun bindings(): kotlin.collections.List<$API.WasmExportBinding> =")
            appendLine("        emptyList()")
        } else {
            appendLine("    public fun bindings(): kotlin.collections.List<$API.WasmExportBinding> =")
            appendLine("        listOf(")
            boundary.functions.forEachIndexed { index, function ->
                val dispatchName = dispatchName(index, function)
                appendLine("            $API.WasmExportBinding(")
                appendLine("                boundary = ${stringLiteral(boundary.wireName)},")
                appendLine("                function = ${stringLiteral(function.wireName)},")
                appendLine("                isSuspend = ${function.isSuspend},")
                appendLine("            ) { payload -> ${identifier(dispatchName)}(payload) },")
            }
            appendLine("        )")
        }
        appendLine()
        appendLine(
            "    public fun install(): kotlin.Unit = " +
                "$API.WasmGuestExportRegistry.install(bindings())",
        )
        if (boundary.functions.isNotEmpty()) {
            appendLine()
            boundary.functions.forEachIndexed { index, function ->
                val suspendPrefix = if (function.isSuspend) "suspend " else ""
                appendLine(
                    "    public ${suspendPrefix}fun ${identifier(dispatchName(index, function))}(" +
                        "payload: kotlin.ByteArray): kotlin.ByteArray {",
                )
                renderDispatchBody(
                    function = function,
                    payloadName = "payload",
                    indent = "        ",
                    explicitReturn = true,
                )
                appendLine("    }")
                if (index != boundary.functions.lastIndex) appendLine()
            }
        }
        appendLine("}")
    }

    private fun StringBuilder.renderDispatchBody(
        function: FunctionModel,
        payloadName: String,
        indent: String,
        explicitReturn: Boolean,
    ) {
        appendLine(
            "${indent}val _kwasmArguments = " +
                "$API.WasmAbiArguments($API.WasmAbiCodec.decode($payloadName))",
        )
        appendLine("${indent}_kwasmArguments.requireSize(${function.parameters.size})")
        val call = "implementation.${identifier(function.kotlinName)}(" +
            function.parameters.mapIndexed { index, parameter ->
                decodeValue(parameter.type, "_kwasmArguments", index)
            }.joinToString(", ") +
            ")"
        if (function.returnType == AbiKotlinType.UNIT) {
            appendLine("$indent$call")
            appendLine(
                indent +
                    (if (explicitReturn) "return " else "") +
                    "$API.WasmAbiCodec.encode(emptyList())",
            )
        } else {
            appendLine("${indent}val _kwasmReturnValue = $call")
            appendLine(
                indent +
                    (if (explicitReturn) "return " else "") +
                    "$API.WasmAbiCodec.encode(" +
                    "listOf(${encodeValue(function.returnType, "_kwasmReturnValue")}))",
            )
        }
    }

    private fun StringBuilder.renderDecodeReturn(
        returnType: BoundaryKotlinType,
        encodedResultName: String,
        decodedValuesName: String,
        indent: String,
    ) {
        appendLine(
            "${indent}val $decodedValuesName = " +
                "$API.WasmAbiArguments($API.WasmAbiCodec.decode($encodedResultName))",
        )
        if (returnType == AbiKotlinType.UNIT) {
            appendLine("${indent}$decodedValuesName.requireSize(0)")
            appendLine("${indent}return")
        } else {
            appendLine("${indent}$decodedValuesName.requireSize(1)")
            appendLine(
                "${indent}return ${decodeValue(returnType, decodedValuesName, 0)}",
            )
        }
    }

    private fun encodeParameters(parameters: List<ParameterModel>): String =
        if (parameters.isEmpty()) {
            "$API.WasmAbiCodec.encode(emptyList())"
        } else {
            "$API.WasmAbiCodec.encode(listOf(" +
                parameters.joinToString(", ") {
                    encodeValue(it.type, identifier(it.name))
                } +
                "))"
        }

    private fun encodeValue(type: BoundaryKotlinType, expression: String): String =
        when (type) {
            is AbiKotlinType -> {
                check(type.valueClassName != null) { "Unit is not encoded as a value" }
                "$API.WasmAbiValue.${type.valueClassName}($expression)"
            }
            is CompositeKotlinType ->
                "$API.WasmAbiValue.Composite(" +
                    "$API.WasmCompositeCodec.encode(" +
                    "${type.qualifiedName}.serializer(), $expression))"
        }

    private fun decodeValue(
        type: BoundaryKotlinType,
        argumentsName: String,
        index: Int,
    ): String =
        when (type) {
            is AbiKotlinType -> {
                check(type.argumentAccessor != null) { "Unit is not decoded as a value" }
                "$argumentsName.${type.argumentAccessor}($index)"
            }
            is CompositeKotlinType ->
                "$API.WasmCompositeCodec.decode(" +
                    "${type.qualifiedName}.serializer(), " +
                    "$argumentsName.composite($index))"
        }

    private fun dispatchName(index: Int, function: FunctionModel): String =
        "_kwasmDispatch${index}_${function.kotlinName}"

    private fun identifier(value: String): String = "`$value`"

    private fun uniqueIdentifier(preferred: String, occupied: List<String>): String {
        var result = preferred
        while (result in occupied) result += "_"
        return identifier(result)
    }

    private fun stringLiteral(value: String): String = buildString {
        append('"')
        value.forEach { character ->
            when (character) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '$' -> append("\\$")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                '\b' -> append("\\b")
                else -> {
                    if (character.code < 0x20) {
                        append("\\u")
                        append(character.code.toString(16).padStart(4, '0'))
                    } else {
                        append(character)
                    }
                }
            }
        }
        append('"')
    }

    private enum class ClientKind {
        HOST,
        GUEST,
    }

    private companion object {
        const val API: String = "io.heapy.kwasm.bindgen"
    }
}

internal enum class BindingTarget {
    PORTABLE,
    WASM,
}
