package io.heapy.kwasm.bindgen.ksp

/**
 * Emits the single raw Kotlin/Wasm transport for one KSP compilation.
 *
 * Boundary-specific generated files install typed handlers into
 * `WasmGuestExportRegistry`; this file owns the compiler-recognized imports,
 * exports, and unmanaged-memory copying shared by all those boundaries.
 */
internal class WasmGuestRuntimeRenderer {
    fun render(): String =
        """
        // Generated by kwasm bindgen. Do not edit.
        @file:OptIn(
            io.heapy.kwasm.ExperimentalKwasmApi::class,
            kotlin.wasm.ExperimentalWasmInterop::class,
            kotlin.wasm.unsafe.ComponentModelInternalApi::class,
            kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class,
        )
        @file:Suppress("RedundantVisibilityModifier")

        package io.heapy.kwasm.bindgen.generated

        import io.heapy.kwasm.bindgen.WasmGuestExportRegistry
        import io.heapy.kwasm.bindgen.WasmGuestInvoker
        import io.heapy.kwasm.bindgen.WasmGuestRuntimeAbi
        import io.heapy.kwasm.bindgen.WasmGuestRuntimeLimits
        import io.heapy.kwasm.bindgen.WasmGuestRuntimeRequestCodec
        import kotlin.wasm.WasmExport
        import kotlin.wasm.WasmImport
        import kotlin.wasm.unsafe.Pointer
        import kotlin.wasm.unsafe.componentModelRealloc
        import kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory
        import kotlin.wasm.unsafe.withScopedMemoryAllocator

        @WasmImport(
            module = WasmGuestRuntimeAbi.HOST_IMPORT_MODULE,
            name = WasmGuestRuntimeAbi.HOST_BEGIN_IMPORT,
        )
        private external fun kwasmBindgenHostBegin(
            requestPointer: Int,
            requestSize: Int,
        ): Long

        @WasmImport(
            module = WasmGuestRuntimeAbi.HOST_IMPORT_MODULE,
            name = WasmGuestRuntimeAbi.HOST_FINISH_IMPORT,
        )
        private external fun kwasmBindgenHostFinish(
            callId: Int,
            resultPointer: Int,
            resultCapacity: Int,
        ): Int

        /**
         * Blocking guest-to-host transport.
         *
         * `begin` executes the host implementation once and returns the call id
         * in bits 0..31 and result length in bits 32..63. `finish` writes and
         * consumes that pending result. Calling `finish(id, 0, 0)` cancels it.
         * A zero-length result still passes its one-byte allocation capacity,
         * keeping address zero distinct from that cancellation sentinel.
         */
        public object KwasmWasmGuestInvoker : WasmGuestInvoker {
            private val limits: WasmGuestRuntimeLimits = WasmGuestRuntimeLimits()

            override fun invoke(
                boundary: String,
                function: String,
                arguments: ByteArray,
            ): ByteArray {
                val request = WasmGuestRuntimeRequestCodec.encode(
                    boundary = boundary,
                    function = function,
                    arguments = arguments,
                    limits = limits,
                )
                return withScopedMemoryAllocator { allocator ->
                    val requestPointer = allocator.allocate(request.size).address.toInt()
                    request.copyToLinearMemory(requestPointer)
                    val packed = kwasmBindgenHostBegin(requestPointer, request.size)
                    val callId = packed.toInt()
                    val resultLengthBits = packed.toULong() shr 32
                    var finished = false
                    try {
                        check(resultLengthBits <= Int.MAX_VALUE.toULong()) {
                            "kwasm host result length ${'$'}resultLengthBits exceeds wasm32"
                        }
                        val resultLength = resultLengthBits.toInt()
                        check(resultLength <= limits.maxResultBytes) {
                            "kwasm host result length ${'$'}resultLength exceeds limit " +
                                "${'$'}{limits.maxResultBytes}"
                        }
                        // Keep zero-length completion distinct from the
                        // finish(id, 0, 0) cancellation sentinel.
                        val allocationSize = if (resultLength == 0) 1 else resultLength
                        val resultPointer = allocator.allocate(allocationSize).address.toInt()
                        val written = kwasmBindgenHostFinish(
                            callId,
                            resultPointer,
                            allocationSize,
                        )
                        finished = true
                        check(written == resultLength) {
                            "kwasm host wrote ${'$'}written result bytes; expected ${'$'}resultLength"
                        }
                        ByteArray(resultLength).also {
                            it.copyFromLinearMemory(resultPointer)
                        }
                    } finally {
                        if (!finished) {
                            // Host registration must consume this as a
                            // cancellation and release the pending result.
                            kwasmBindgenHostFinish(callId, 0, 0)
                        }
                    }
                }
            }
        }

        private val kwasmGuestAllocations: MutableMap<Int, Int> = mutableMapOf()

        @WasmExport(WasmGuestRuntimeAbi.ALLOCATE_EXPORT)
        private fun kwasmBindgenAllocate(size: Int): Int {
            require(size > 0) { "kwasm guest allocation size must be positive" }
            val pointer = componentModelRealloc(
                originalPtr = 0,
                originalSize = 0,
                newSize = size,
            )
            check(pointer >= 0) { "kwasm guest allocator returned a negative pointer" }
            check(kwasmGuestAllocations.put(pointer, size) == null) {
                "kwasm guest allocator reused live pointer ${'$'}pointer"
            }
            return pointer
        }

        @WasmExport(WasmGuestRuntimeAbi.FREE_EXPORT)
        private fun kwasmBindgenFree(pointer: Int, size: Int) {
            val allocatedSize = kwasmGuestAllocations.remove(pointer)
                ?: error("kwasm guest free references unknown pointer ${'$'}pointer")
            check(allocatedSize == size) {
                "kwasm guest free size ${'$'}size does not match allocation ${'$'}allocatedSize"
            }
            if (kwasmGuestAllocations.isEmpty()) {
                freeAllComponentModelReallocAllocatedMemory()
            }
        }

        @WasmExport(WasmGuestRuntimeAbi.INVOKE_EXPORT)
        private fun kwasmBindgenInvoke(
            requestPointer: Int,
            requestSize: Int,
        ): Long {
            require(requestPointer >= 0) { "kwasm request pointer must be non-negative" }
            require(requestSize >= WasmGuestRuntimeAbi.REQUEST_HEADER_SIZE) {
                "kwasm request is shorter than the runtime header"
            }
            val encodedRequest = ByteArray(requestSize).also {
                it.copyFromLinearMemory(requestPointer)
            }
            val request = WasmGuestRuntimeRequestCodec.decode(encodedRequest)
            val result = WasmGuestExportRegistry.dispatchBlocking(
                boundary = request.boundary,
                function = request.function,
                arguments = request.arguments,
            )
            val resultPointer = kwasmBindgenAllocate(result.size)
            result.copyToLinearMemory(resultPointer)
            return (result.size.toLong() shl 32) or
                (resultPointer.toLong() and 0xFFFF_FFFFL)
        }

        private fun ByteArray.copyToLinearMemory(pointer: Int) {
            var index = 0
            while (index < size) {
                Pointer((pointer + index).toUInt()).storeByte(this[index])
                index += 1
            }
        }

        private fun ByteArray.copyFromLinearMemory(pointer: Int) {
            var index = 0
            while (index < size) {
                this[index] = Pointer((pointer + index).toUInt()).loadByte()
                index += 1
            }
        }
        """.trimIndent() + "\n"
}
