package io.heapy.kwasm.tck

import io.heapy.kwasm.ExecutionLimits
import io.heapy.kwasm.Store
import io.heapy.kwasm.StoreConfig
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.nameWithoutExtension
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.runBlocking

private const val GENERATED_DIRECTORY_PROPERTY: String = "kwasm.tck.generatedDir"
private const val EXCLUSIONS_DIRECTORY_PROPERTY: String = "kwasm.tck.exclusionsDir"
private const val TCK_MAX_FRAMES: Int = 4_096

/**
 * JVM entry point for a corpus generated by [WABT](https://github.com/WebAssembly/wabt).
 *
 * Gradle only supplies [GENERATED_DIRECTORY_PROPERTY] when
 * `-Pkwasm.tck.wastDir` is configured. Consequently a normal repository test
 * run remains a fast no-op, while an explicitly configured run fails if the
 * generated directory is empty or malformed.
 */
class GeneratedSpecCorpusTest {
    @Test
    fun generatedSpecCorpus() = runBlocking {
        val summary = executeConfiguredCorpus(System.getProperties().stringEntries())
            ?: return@runBlocking

        println(summary.description())
        summary.requireSuccess()
    }

    @Test
    fun absentCorpusConfigurationIsANoOp() = runBlocking {
        assertNull(executeConfiguredCorpus(emptyMap()))
    }

    @Test
    fun adapterExecutesSyntheticGeneratedAssetsAndLoadsExclusions() = runBlocking {
        val temporaryRoot = Files.createTempDirectory("kwasm-generated-tck-")
        try {
            val generated = Files.createDirectory(temporaryRoot.resolve("generated"))
            val exclusions = Files.createDirectory(temporaryRoot.resolve("exclusions"))
            val nested = Files.createDirectories(generated.resolve("nested/core"))

            Files.writeString(
                nested.resolve("smoke.json"),
                """
                {
                  "source_filename": "synthetic/smoke.wast",
                  "commands": [
                    {
                      "type": "assert_malformed",
                      "line": 1,
                      "filename": "smoke.0.wasm",
                      "module_type": "binary",
                      "text": "magic header not detected"
                    }
                  ]
                }
                """.trimIndent(),
            )
            Files.writeString(
                nested.resolve("smoke.0.wasm"),
                "not a WebAssembly binary",
            )
            Files.writeString(
                generated.resolve("excluded.json"),
                """
                {
                  "source_filename": "synthetic/excluded.wast",
                  "commands": [
                    {
                      "type": "assert_malformed",
                      "line": 9,
                      "filename": "missing-by-design.wasm",
                      "module_type": "binary",
                      "text": "excluded before asset loading"
                    }
                  ]
                }
                """.trimIndent(),
            )
            Files.writeString(
                exclusions.resolve("synthetic.txt"),
                "synthetic/excluded.wast:9 https://github.com/heapy/kwasm/issues/9999\n",
            )

            val summary = requireNotNull(
                executeConfiguredCorpus(
                    mapOf(
                        GENERATED_DIRECTORY_PROPERTY to generated.toString(),
                        EXCLUSIONS_DIRECTORY_PROPERTY to exclusions.toString(),
                    ),
                ),
            )

            summary.requireSuccess()
            assertEquals(2, summary.manifests)
            assertEquals(2, summary.commands)
            assertEquals(1, summary.passed)
            assertEquals(1, summary.excluded)
        } finally {
            temporaryRoot.toFile().deleteRecursively()
        }
    }
}

private data class JvmCorpusSummary(
    val reports: List<TckReport>,
    val manifestFailures: List<ManifestFailure>,
) {
    val manifests: Int get() = reports.size + manifestFailures.size
    val commands: Int get() = reports.sumOf { it.results.size }
    val passed: Int get() = reports.sumOf(TckReport::passed)
    val failed: Int get() = reports.sumOf(TckReport::failed)
    val excluded: Int get() = reports.sumOf(TckReport::excluded)

    fun description(): String =
        "kwasm generated TCK: $manifests manifest(s), $commands command(s), " +
            "$passed passed, $failed failed, $excluded excluded, " +
            "${manifestFailures.size} manifest error(s)"

    fun requireSuccess() {
        if (failed == 0 && manifestFailures.isEmpty()) return
        throw AssertionError(
            buildString {
                append(description())
                reports.asSequence()
                    .filter { it.failed > 0 }
                    .sortedByDescending(TckReport::failed)
                    .take(20)
                    .forEach { report ->
                        append(
                            "\n  ${report.sourceFilename}: " +
                                "${report.passed} passed, ${report.failed} failed, " +
                                "${report.excluded} excluded",
                        )
                    }
                manifestFailures.take(20).forEach { failure ->
                    append("\n  ${failure.manifest}: ${failure.detail}")
                }
                reports.asSequence()
                    .flatMap { report ->
                        report.results.asSequence()
                            .filter { it.outcome == TckOutcome.Failed }
                            .map { result ->
                                "  ${report.sourceFilename}:${result.line} " +
                                    "${result.command}: ${result.detail}"
                            }
                    }
                    .take(50)
                    .forEach { failure -> append("\n$failure") }
            },
        )
    }
}

private data class ManifestFailure(
    val manifest: String,
    val detail: String,
)

private suspend fun executeConfiguredCorpus(
    properties: Map<String, String>,
): JvmCorpusSummary? {
    val configuredDirectory = properties[GENERATED_DIRECTORY_PROPERTY]
        ?.takeIf(String::isNotBlank)
        ?: return null
    val exclusionsDirectory = properties[EXCLUSIONS_DIRECTORY_PROPERTY]
        ?.takeIf(String::isNotBlank)
        ?: error(
            "$EXCLUSIONS_DIRECTORY_PROPERTY must be set when " +
                "$GENERATED_DIRECTORY_PROPERTY is configured",
        )

    val generatedRoot = Path.of(configuredDirectory).toRealPath()
    require(Files.isDirectory(generatedRoot)) {
        "Generated TCK path is not a directory: $generatedRoot"
    }
    val exclusions = loadExclusions(Path.of(exclusionsDirectory))
    val manifests = generatedRoot.toFile()
        .walkTopDown()
        .filter { it.isFile && it.extension.equals("json", ignoreCase = true) }
        .map { it.toPath() }
        .sortedBy { generatedRoot.relativize(it).toString().replace('\\', '/') }
        .toList()
    require(manifests.isNotEmpty()) {
        "Configured TCK corpus generated no wast2json manifests below $generatedRoot"
    }

    val reports = mutableListOf<TckReport>()
    val manifestFailures = mutableListOf<ManifestFailure>()
    manifests.forEach { manifest ->
        val relativeManifest = generatedRoot.relativize(manifest).toString().replace('\\', '/')
        try {
            val realManifest = manifest.toRealPath()
            require(realManifest.startsWith(generatedRoot)) {
                "Manifest escapes generated corpus root: $relativeManifest"
            }
            val script = WastScript.parse(
                Files.readString(realManifest, StandardCharsets.UTF_8),
            )
            val assets = confinedAssetLoader(generatedRoot, realManifest.parent)
            reports += WastRunner(
                assets = assets,
                exclusions = exclusions,
                // Spec exhaustion tests intentionally recurse without a base
                // case. Keep the conformance harness below the host's memory
                // ceiling so the engine reports its deterministic guest-frame
                // trap before the JVM can throw OutOfMemoryError.
                storeFactory = {
                    Store(StoreConfig(limits = ExecutionLimits(maxFrames = TCK_MAX_FRAMES)))
                },
            ).run(script)
        } catch (cancellation: CancellationException) {
            throw cancellation
        } catch (failure: Exception) {
            manifestFailures += ManifestFailure(
                relativeManifest,
                failure.message ?: failure::class.qualifiedName ?: "unknown manifest failure",
            )
        }
    }

    return JvmCorpusSummary(reports, manifestFailures)
}

private fun loadExclusions(directory: Path): TckExclusions {
    val root = directory.toRealPath()
    require(Files.isDirectory(root)) {
        "TCK exclusions path is not a directory: $root"
    }
    return root.toFile()
        .walkTopDown()
        .filter { it.isFile && it.extension.equals("txt", ignoreCase = true) }
        .map { it.toPath() }
        .sortedBy { root.relativize(it).toString().replace('\\', '/') }
        .fold(TckExclusions.Empty) { combined, file ->
            combined + TckExclusions.parse(
                feature = file.nameWithoutExtension,
                text = Files.readString(file, StandardCharsets.UTF_8),
            )
        }
}

private fun confinedAssetLoader(
    generatedRoot: Path,
    manifestDirectory: Path,
): TckAssetLoader = TckAssetLoader { filename ->
    val portableFilename = filename.replace('\\', '/')
    val relative = Path.of(portableFilename)
    require(!relative.isAbsolute) {
        "wast2json manifest requested an absolute asset path: '$filename'"
    }
    val asset = manifestDirectory.resolve(relative).normalize().toRealPath()
    require(asset.startsWith(generatedRoot)) {
        "wast2json asset escapes generated corpus root: '$filename'"
    }
    Files.readAllBytes(asset)
}

private fun java.util.Properties.stringEntries(): Map<String, String> =
    stringPropertyNames().associateWith(::getProperty)
