@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package io.heapy.kwasm.tck

import io.heapy.kwasm.ExecutionLimits
import io.heapy.kwasm.Store
import io.heapy.kwasm.StoreConfig
import kotlinx.cinterop.addressOf
import kotlinx.cinterop.pointed
import kotlinx.cinterop.toKString
import kotlinx.cinterop.usePinned
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.runBlocking
import platform.posix.DT_DIR
import platform.posix.DT_LNK
import platform.posix.DT_REG
import platform.posix.SEEK_END
import platform.posix.closedir
import platform.posix.fclose
import platform.posix.fopen
import platform.posix.fread
import platform.posix.free
import platform.posix.fseek
import platform.posix.ftell
import platform.posix.getenv
import platform.posix.opendir
import platform.posix.posix_errno
import platform.posix.readdir
import platform.posix.realpath
import platform.posix.rewind
import kotlin.test.Test
import kotlin.test.assertNull

/**
 * Kotlin/Native entry point for a corpus generated by WABT.
 *
 * Gradle only supplies [GENERATED_DIRECTORY_ENVIRONMENT] to the standalone
 * Native test binary that matches the current macOS or Linux host. Device and
 * simulator tests, cross-compiled targets, and ordinary unconfigured builds
 * therefore skip without touching the host file system.
 */
class GeneratedSpecCorpusNativeTest {
    @Test
    fun generatedSpecCorpus() = runBlocking {
        val summary = executeConfiguredNativeCorpus(
            generatedDirectory = environment(GENERATED_DIRECTORY_ENVIRONMENT),
            exclusionsDirectory = environment(EXCLUSIONS_DIRECTORY_ENVIRONMENT),
        ) ?: return@runBlocking

        println(summary.description())
        summary.requireSuccess()
    }

    @Test
    fun absentCorpusConfigurationIsANoOp() = runBlocking {
        assertNull(
            executeConfiguredNativeCorpus(
                generatedDirectory = null,
                exclusionsDirectory = null,
            ),
        )
    }
}

private data class NativeCorpusSummary(
    val reports: List<TckReport>,
    val manifestFailures: List<NativeManifestFailure>,
) {
    val manifests: Int get() = reports.size + manifestFailures.size
    val commands: Int get() = reports.sumOf { it.results.size }
    val passed: Int get() = reports.sumOf(TckReport::passed)
    val failed: Int get() = reports.sumOf(TckReport::failed)
    val excluded: Int get() = reports.sumOf(TckReport::excluded)

    fun description(): String =
        "kwasm generated Native TCK: $manifests manifest(s), $commands command(s), " +
            "$passed passed, $failed failed, $excluded excluded, " +
            "${manifestFailures.size} manifest error(s)"

    fun requireSuccess() {
        if (failed == 0 && manifestFailures.isEmpty()) return
        throw AssertionError(
            buildString {
                append(description())
                reports.asSequence()
                    .filter { it.failed > 0 }
                    .sortedByDescending(TckReport::failed)
                    .take(20)
                    .forEach { report ->
                        append(
                            "\n  ${report.sourceFilename}: " +
                                "${report.passed} passed, ${report.failed} failed, " +
                                "${report.excluded} excluded",
                        )
                    }
                manifestFailures.take(20).forEach { failure ->
                    append("\n  ${failure.manifest}: ${failure.detail}")
                }
                reports.asSequence()
                    .flatMap { report ->
                        report.results.asSequence()
                            .filter { it.outcome == TckOutcome.Failed }
                            .map { result ->
                                "  ${report.sourceFilename}:${result.line} " +
                                    "${result.command}: ${result.detail}"
                            }
                    }
                    .take(50)
                    .forEach { failure -> append("\n$failure") }
            },
        )
    }
}

private data class NativeManifestFailure(
    val manifest: String,
    val detail: String,
)

private suspend fun executeConfiguredNativeCorpus(
    generatedDirectory: String?,
    exclusionsDirectory: String?,
): NativeCorpusSummary? {
    val configuredDirectory = generatedDirectory?.takeIf(String::isNotBlank) ?: return null
    val configuredExclusions = exclusionsDirectory?.takeIf(String::isNotBlank)
        ?: error(
            "$EXCLUSIONS_DIRECTORY_ENVIRONMENT must be set when " +
                "$GENERATED_DIRECTORY_ENVIRONMENT is configured",
        )

    val generatedRoot = canonicalPath(configuredDirectory)
    val exclusionsRoot = canonicalPath(configuredExclusions)
    val exclusions = loadNativeExclusions(exclusionsRoot)
    val manifests = walkConfinedRegularFiles(generatedRoot)
        .filter { it.relative.endsWith(".json", ignoreCase = true) }
        .sortedBy(NativeCorpusFile::relative)
    require(manifests.isNotEmpty()) {
        "Configured Native TCK corpus contains no wast2json manifests below $generatedRoot"
    }

    val reports = mutableListOf<TckReport>()
    val manifestFailures = mutableListOf<NativeManifestFailure>()
    manifests.forEach { manifest ->
        try {
            val manifestPath = canonicalConfinedPath(
                root = generatedRoot,
                candidate = joinPath(generatedRoot, manifest.relative),
                description = "manifest '${manifest.relative}'",
            )
            val script = WastScript.parse(
                readNativeBytes(manifestPath).decodeToString(throwOnInvalidSequence = true),
            )
            reports += WastRunner(
                assets = confinedNativeAssetLoader(
                    generatedRoot = generatedRoot,
                    manifestDirectory = manifestPath.substringBeforeLast('/'),
                ),
                exclusions = exclusions,
                storeFactory = {
                    Store(StoreConfig(limits = ExecutionLimits(maxFrames = TCK_MAX_FRAMES)))
                },
            ).run(script)
        } catch (cancellation: CancellationException) {
            throw cancellation
        } catch (failure: Exception) {
            manifestFailures += NativeManifestFailure(
                manifest = manifest.relative,
                detail = failure.message ?: failure::class.simpleName ?: "unknown manifest failure",
            )
        }
    }

    return NativeCorpusSummary(reports, manifestFailures)
}

private fun loadNativeExclusions(root: String): TckExclusions =
    walkConfinedRegularFiles(root)
        .filter { it.relative.endsWith(".txt", ignoreCase = true) }
        .sortedBy(NativeCorpusFile::relative)
        .fold(TckExclusions.Empty) { combined, file ->
            val path = canonicalConfinedPath(
                root = root,
                candidate = joinPath(root, file.relative),
                description = "exclusion '${file.relative}'",
            )
            combined + TckExclusions.parse(
                feature = file.relative.substringAfterLast('/').removeSuffix(".txt"),
                text = readNativeBytes(path).decodeToString(throwOnInvalidSequence = true),
            )
        }

private fun confinedNativeAssetLoader(
    generatedRoot: String,
    manifestDirectory: String,
): TckAssetLoader = TckAssetLoader { filename ->
    val portableFilename = filename.replace('\\', '/')
    require(
        portableFilename.isNotEmpty() &&
            '\u0000' !in portableFilename &&
            !portableFilename.startsWith('/') &&
            !WINDOWS_ABSOLUTE_PATH.containsMatchIn(portableFilename),
    ) {
        "wast2json manifest requested an absolute or invalid asset path: '$filename'"
    }
    val asset = canonicalConfinedPath(
        root = generatedRoot,
        candidate = joinPath(manifestDirectory, portableFilename),
        description = "wast2json asset '$filename'",
    )
    readNativeBytes(asset)
}

private data class NativeCorpusFile(
    val relative: String,
)

/**
 * Recursively discovers only regular files below [root].
 *
 * Generated WABT output and checked-in exclusions are expected to contain
 * directories and regular files only. Rejecting symlinks, sockets, and
 * unknown directory-entry types keeps discovery fail-closed on both macOS and
 * Linux instead of silently traversing a path outside the configured root.
 */
private fun walkConfinedRegularFiles(root: String): List<NativeCorpusFile> {
    val files = mutableListOf<NativeCorpusFile>()
    walkConfinedRegularFiles(root, "", files)
    return files
}

private fun walkConfinedRegularFiles(
    root: String,
    relativeDirectory: String,
    files: MutableList<NativeCorpusFile>,
) {
    val directoryPath =
        if (relativeDirectory.isEmpty()) root else joinPath(root, relativeDirectory)
    val canonicalDirectory = canonicalConfinedPath(
        root = root,
        candidate = directoryPath,
        description = "directory '$relativeDirectory'",
    )
    val directory = opendir(canonicalDirectory)
        ?: error("Cannot open directory '$canonicalDirectory' (errno ${posix_errno()})")
    try {
        while (true) {
            val entry = readdir(directory) ?: break
            val name = entry.pointed.d_name.toKString()
            if (name == "." || name == "..") continue
            require('/' !in name && '\u0000' !in name) {
                "Invalid directory entry below '$canonicalDirectory'"
            }
            val relative =
                if (relativeDirectory.isEmpty()) name else "$relativeDirectory/$name"
            when (entry.pointed.d_type.toInt()) {
                DT_DIR -> walkConfinedRegularFiles(root, relative, files)
                DT_REG -> files += NativeCorpusFile(relative)
                DT_LNK -> error("Symlink is not allowed in confined TCK input: '$relative'")
                else -> error(
                    "Special or unknown file is not allowed in confined TCK input: '$relative'",
                )
            }
        }
    } finally {
        closedir(directory)
    }
}

private fun canonicalConfinedPath(
    root: String,
    candidate: String,
    description: String,
): String {
    val canonical = canonicalPath(candidate)
    require(canonical == root || canonical.startsWith(confinedPrefix(root))) {
        "$description escapes configured TCK root '$root': '$canonical'"
    }
    return canonical
}

private fun canonicalPath(path: String): String {
    require(path.isNotBlank() && '\u0000' !in path) { "Invalid empty or NUL-containing path" }
    val resolved = realpath(path, null)
        ?: error("Cannot resolve path '$path' (errno ${posix_errno()})")
    return try {
        resolved.toKString()
    } finally {
        free(resolved)
    }
}

private fun readNativeBytes(path: String): ByteArray {
    val file = fopen(path, "rb")
        ?: error("Cannot open file '$path' (errno ${posix_errno()})")
    try {
        check(fseek(file, 0, SEEK_END) == 0) {
            "Cannot seek file '$path' (errno ${posix_errno()})"
        }
        val length = ftell(file)
        check(length >= 0 && length <= Int.MAX_VALUE) {
            "File '$path' has unsupported size $length"
        }
        rewind(file)
        val bytes = ByteArray(length.toInt())
        if (bytes.isNotEmpty()) {
            val count = bytes.usePinned { pinned ->
                fread(pinned.addressOf(0), 1uL, bytes.size.toULong(), file)
            }
            check(count == bytes.size.toULong()) {
                "Short read for '$path': expected ${bytes.size}, got $count"
            }
        }
        return bytes
    } finally {
        fclose(file)
    }
}

private fun environment(name: String): String? =
    getenv(name)?.toKString()?.takeIf(String::isNotBlank)

private fun confinedPrefix(root: String): String =
    if (root == "/") root else "${root.trimEnd('/')}/"

private fun joinPath(
    parent: String,
    child: String,
): String = "${parent.trimEnd('/')}/${child.trimStart('/')}"

private val WINDOWS_ABSOLUTE_PATH: Regex = Regex("^[A-Za-z]:/")
private const val GENERATED_DIRECTORY_ENVIRONMENT: String = "KWASM_TCK_GENERATED_DIR"
private const val EXCLUSIONS_DIRECTORY_ENVIRONMENT: String = "KWASM_TCK_EXCLUSIONS_DIR"
private const val TCK_MAX_FRAMES: Int = 4_096
